# Generated by Django 4.2.1 on 2023-05-16 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaFlavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrderBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pizza.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzaorderbasket')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pizza.pizza')),
            ],
            options={
                'unique_together': {('pizza', 'basket')},
            },
        ),
        migrations.AddField(
            model_name='pizzaorderbasket',
            name='pizzas',
            field=models.ManyToManyField(through='pizza.PizzaOrderItem', to='pizza.pizza'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pizza.pizzaflavour'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pizza.pizzasize'),
        ),
        migrations.CreateModel(
            name='OrderResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=10)),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzaorderbasket')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('flavour', 'size')},
        ),
    ]
